config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: %i[show new create edit update destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: %i[index show new create edit update]
  resources :product_models, only: %i[index new create show]

  resources :orders, only: %i[new create show index edit update] do
    resources :order_items, only: %i[new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[show index create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true

  validates :state, length: { is: 2 }

  validates :registration_number, uniqueness: true

  def full_description
    "#{corporate_name} - #{brand_name}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar Fornecedor.'
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state,
                                     :email)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.number_field :registration_number %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_area :full_address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
  <%= f.submit  %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>
          Razão Social
        </th>
        <th>
          Localização
        </th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |s| %>
        <tr>
          <td><%= link_to(s.corporate_name, supplier_path(s.id)) %></td>
          <td><%= s.city %>·-·<%= s.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>Não existem Fornecedores cadastrados</h2>
<% end %>

<%= link_to 'Cadastrar novo Fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>
<% if(@supplier.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<div>
  <%= link_to('Editar', edit_supplier_path(@supplier.id)) %>
</div>

<div>
  <%= link_to('Voltar', root_path) %>
</div>